### ISSUE TITLE
Direct SSL is not sent to Django

### ISSUE THREAD

**Issue by JohnDoee** [django/daphne#100]
When you start up Daphne with SSL enabled and generate absolute URLs in your Django application, the resulting URLs does not use HTTPS, but HTTP.

This results in unusable URLs.

If you want to know if a request is using ssl, use `request.isSecure()`

**Comment by andrewgodwin** [comment]
This has now been fixed in Daphne master.

**Comment by adamoxley** [comment]
Hi Andrew,

I know you said this is now fixed in Daphne master (which I assume falls in line with the release tag 1.2.0)

I am having the same issue as JohnDoee above where I access a HTTPS url endpoint, and the URL generated by the Django application is HTTP. I am seeing this when using LimitOffsetPagination and CursorPagination from the Django Rest Framework.

I initially found this issue and upgraded all the packages on the box, below is my pip freeze list.

```
asgi-redis==1.2.1
asgiref==1.1.1
attrs==16.3.0
autobahn==0.18.1
Automat==0.5.0
boto==2.39.0
channels==1.1.2
constantly==15.1.0
coreapi==2.3.0
coreschema==0.0.4
coverage==4.3.4
daphne==1.2.0
defusedxml==0.4.1
Django==1.10.3
django-cachalot==1.2.0
django-crispy-forms==1.6.0
django-filter==0.12.0
django-queryinspect==0.1.0
django-redis==4.3.0
django-rest-swagger==2.1.0
django-scarface==3.0a8
django-ses==0.8.2
django-storages==1.4
djangorestframework==3.5.3
djangorestframework-xml==1.3.0
ecdsa==0.13
Fabric==1.10.2
filechunkio==1.6
gunicorn==19.4.5
incremental==16.10.1
itypes==1.1.0
Jinja2==2.9.6
MarkupSafe==1.0
msgpack-python==0.4.8
openapi-codec==1.3.1
paramiko==1.16.0
Pillow==3.1.0
psycopg2==2.7.1
pycrypto==2.6.1
python-dateutil==2.6.0
python-memcached==1.57
PyYAML==3.11
redis==2.10.5
requests==2.13.0
simplejson==3.10.0
six==1.10.0
Twisted==17.1.0
txaio==2.6.2
uritemplate==3.0.0
virtualenv==13.1.2
zope.interface==4.3.3
```

Note: I am not running Channels 1.1.3 since pip could not find this (the release was <24 hours ago when I installed it so it gathered 1.1.2)

The front end applications are disallowed from using HTTP due to restrictions that we have set on the Amazon Web Services box to only allow HTTPS traffic and deny HTTP, so when they use the 'next' url generated by Django in pagination, the front end receives a connection refused since it isn't HTTPS.

Example: 

I hit the endpoint on my application `https://url.tld/messages` which sends back to the front end a set of message objects (paginated) and therefore has a 'next' and 'previous' URL generated by Django. This generated URL is sent back in 'next' (or 'previous') as `http://url.tld/messages?limit=10&offset=10`.

Any help would be appreciated.

**Comment by andrewgodwin** [comment]
How are you terminating HTTPS? The fix and native support only applies if you are doing it directly in Daphne, in which case, can I get the CLI command you are using?

**Comment by adamoxley** [comment]
Hi Andrew, thanks for the response.

We are terminating HTTPS at the load balancer. Our set up is load balancer -> EC2 (running Daphne / Channels / Django). Anything that hits the load balancer must be HTTPS to be passed onto the EC2 instance, however once 'inside' the AWS network after the load balancer passes on the request, it is all HTTP.

The command used to start Django is `daphne -b 0.0.0.0 -p 8000 -u /var/projectname/daphne.sock api.asgi:channel_layer`. That `.sock` file is then used in NGINX.

**Comment by andrewgodwin** [comment]
If you're terminating SSL at the load balancer, then you'll need to have that handle signalling for SSL domains, much the same as you would in normal Django. Specifically, it needs to both send a header (usually X-Forwarded-Proto) and then Django should have the setting SECURE_PROXY_SSL_HEADER configured to match (I think - you should look that up in the docs)

**Comment by adamoxley** [comment]
Hi Andrew, that worked great thanks a lot!
