### ISSUE TITLE
Daphne with multiple workers corrupting Sessions. 

### ISSUE THREAD

**Issue by kodeshpa** [django/daphne#137]
I am experiencing weird issues. I am running channels==1.1.6 version. 

Everything works great, no issues with single Daphne server and 1 worker. But moment i scale up and spin another worker, it starts corrupting sessions. I even tried switching to cached DB as session engine.

SESSION_ENGINE="django.contrib.sessions.backends.cached_db"

Am i missing anything? How can i can run multiple workers with 1 Daphne server?

**Comment by andrewgodwin** [comment]
You're doing everything as intended. As this is not a Daphne issue, I'm going to close this - I'd suggest either emailing the django-users mailing list about this, or opening a ticket on the channels repo, and including exact output and expected behaviour of what "corrupting sessions" are (i.e., what do you expect to happen versus what actually happens)
