### ISSUE TITLE
Feature request: Ability to shorten log message

### ISSUE THREAD

**Issue by hongquan** [django/daphne#271]
In my setup, I use systemd to start/stop Daphne server, and use journalctl to see Daphne log.

When viewing via Journalctl, the log line is pretty long and redundant:

```
Jul 03 09:06:05 elevator-acs-c daphne[6223]: DEBUG 2019-07-03 09:06:05,846 consumers 6223 140236757043008 devinfo DeviceUpdate(beacon_mode=False, firmware_available=None, request_reboot=None, request_open_gate=None, floor_number=None, elevator_shaft=None)
Jul 03 09:06:05 elevator-acs-c daphne[6223]: DEBUG 2019-07-03 09:06:05,850 consumers 6223 140236757043008 Device: None
Jul 03 09:06:05 elevator-acs-c daphne[6223]: INFO 2019-07-03 09:06:05,850 consumers 6223 140236757043008 MainMessage(hwid=None, proxy_hwid=None, reg_request=None, reg_response=DeviceRegistrationResponse(device_token='ROznIElDdJnIPSNEUjaJ', result=<RegistrationResult.REG_SUCCESS: 0>), auth_request=None, auth_response=None, device_update=None, call_elevator_request=None, call_elevator_response=None, device_info=None, auth=None)
```

I want to shorten it, maybe by telling Daphne not to print out its timestamp, process ID. Could you add this feature?

**Comment by carltongibson** [comment]
Grrr. You'd need to override [`AccessLogGenerator`](https://github.com/django/daphne/blob/ffd949f2ce3085eb0ea4c4bf45f6b2f60928e809/daphne/access.py#L4) and [make that pluggable in the CLI](https://github.com/django/daphne/blob/ffd949f2ce3085eb0ea4c4bf45f6b2f60928e809/daphne/cli.py#L298).

I'd be happy to look at a PR adding such but it's not something I want to consider an _Open Issue_ otherwise.

**Comment by hongquan** [comment]
Found that in my case, it is the issue of `LOGGING` setting. I should change the `LOGGING['formatters']` value.
