### ISSUE TITLE
Why use daphne over uwsgi?

### ISSUE THREAD

**Issue by caleb15** [django/daphne#328]
Now that uwsgi has [websocket support](https://uwsgi-docs.readthedocs.io/en/latest/WebSockets.html) why use daphne? Not trying to denigrate daphne, just curious what the differences are and the associated drawbacks / advantages.

**Comment by adamchainz** [comment]
uwsgi's websocket support seems to be based on their own interface and not ASGI. So it's not possible to deploly arbitrary apps, and only suitable for websockets rather than all the protocols ASGI can support such as HTTP long polling, server sent events, and extensibility to other protocols.

There's quite a flourishing ASGI ecosystem at this point: https://github.com/florimondmanca/awesome-asgi

**Comment by caleb15** [comment]
Interesting, thanks!

**Comment by caleb15** [comment]
We had performance problems with daphne, in retrospect we should have continued using Uwsgi and taken our time to evaluate other solutions.
