### ISSUE TITLE
Easy syntax to bind on multiple IPs

### ISSUE THREAD

**Issue by p-fruck** [django/daphne#521]
It seems like daphne is unable to bind to multiple IPs with a simple syntax. The only way I was able to achieve such behavior, e.g. to listen on IPv4 and IPv6 simultaneously, is the following: `daphne -e "tcp:8005:interface=0.0.0.0" -b ::1 -p 8005`

I would expect daphne to allow for a simpler syntax than this. Additionally, I was unable to bind to an IPv6 address using the endpoint notation. `daphne -e "tcp:8005:interface=::1"` as well as `daphne -e "tcp:8005:interface=[::1]"` result in the following error message: `TypeError: _parseTCP() got multiple values for argument 'interface'`

**Comment by bigfootjon** [comment]
As I see it, you've got 2 problems:

1. `-e` with an IPv6 address isn't working
2. Specifying multiple binds is complex

For (1) I think the problem is that `:` is the separator for twisted endpoints, so you need to escape it. This should work:

```
daphne -e "tcp:8005:interface=\:\:1" 
```

(it worked for me locally)

For (2) I think that the current implementation makes sense:

1. For "simple" configuration provide nothing or specify `-b` and/or `-p` as needed
2. For "complex" configuration you have to specify the full Twisted endpoint for each one (you can use `-e` multiple times)

This setup seems pretty sensible to me. Do you have any thoughts about how this could be better designed?

**Comment by p-fruck** [comment]
Thanks for the reply, this makes sense to me. Intuitively I expected the -p option to bind on 127.0.0.1 as well as ::1. Also it is surprising to me that -e can be specified multiple times whereas -b seems like it can only be used once. Is there a specific reason for that?

**Comment by carltongibson** [comment]
`-b` is convenience wrapper over the underlying endpoints approach for common cases. Multiple binds is a more niche and so you drop down to the lower level API
