### ISSUE TITLE
Running multiple insatnce of daphne?

### ISSUE THREAD

**Issue by kosiraljaz** [django/daphne#79]
How does one run multiple insatnces in daphe, is there some parameter like in gunicorn to set number of workers?

Do I just run multiple isntances, if I want 3 workers:
```
daphne -b 127.0.0.1 -p 8001 restapi.asgi:channel_layer
daphne -b 127.0.0.1 -p 8001 restapi.asgi:channel_layer
daphne -b 127.0.0.1 -p 8001 restapi.asgi:channel_layer
```

This seems strange since they all bind to same port?

**Comment by andrewgodwin** [comment]
Daphne is asynchronous code, it doesn't need worker threads like gunicorn. If you want multiple processes (you should have maximum 1 per physical core on the machine), then run them as separate instances and use nginx/haproxy/or similar to loadbalance across them.

**Comment by adihat** [comment]
@andrewgodwin so to clarify, if one has 5 nodes, it's recommended to setup a single daphne process on each machine and then use an application load balancer across them?

**Comment by tomchristie** [comment]
@adihat Typically you'll want to run multiple processes on each instance. (One-per-core will generally work well.) And yes, then use load balancers to distribute between the multiple processes and multiple instances.

**Comment by udipercepto** [comment]
@andrewgodwin I am using nginx to load balance between 2 daphne processes and I see sometimes these kind of messages  -
[daphne.http_protocol:365] Message on unknown channel u'daphne.response.PBWpKJGGxs!dJnxtfaczV' - discarding
I thought it because a websocket client that has a response channel on one daphne is balanced to the other. Is it possible? and if so, how can I work with more than one daphne on a specific machine with nginx?
Thank you
